"""Add is_active to Player model

Revision ID: 0505c1fe36ee
Revises: c71dd35b4745
Create Date: 2025-11-17 17:07:02.943514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0505c1fe36ee'
down_revision: Union[str, Sequence[str], None] = 'c71dd35b4745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_active')
    # ### end Alembic commands ###
