"""fix cascade delete topics and cards related with these topic

Revision ID: 3a87a08e4927
Revises: 
Create Date: 2025-11-16 17:07:12.621082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a87a08e4927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_topic_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_topic_id_fkey'), 'cards', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###
